config:
  WOLF:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 10
    DEER: 15
    RABBIT: 60
    MOUSE: 80
    GOAT: 60
    SHEEP: 70
    BOAR: 15
    BUFFALO: 10
    DUCK: 40
    CATERPILLAR: 0
    GRASS: 0

  BOA:
    WOLF: 0
    BOA: 0
    FOX: 15
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 20
    MOUSE: 40
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 10
    CATERPILLAR: 0
    GRASS: 0

  FOX:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 70
    MOUSE: 90
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 60
    CATERPILLAR: 100
    GRASS: 0

  BEAR:
    WOLF: 0
    BOA: 80
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 40
    DEER: 80
    RABBIT: 80
    MOUSE: 90
    GOAT: 70
    SHEEP: 70
    BOAR: 50
    BUFFALO: 20
    DUCK: 10
    CATERPILLAR: 0
    GRASS: 0

  EAGLE:
    WOLF: 0
    BOA: 0
    FOX: 10
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 90
    MOUSE: 90
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 80
    CATERPILLAR: 0
    GRASS: 0

  HORSE:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100

  DEER:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100

  RABBIT:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100

  MOUSE:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 100
    GRASS: 100

  GOAT:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100

  SHEEP:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100

  BOAR:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 50
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 100
    GRASS: 100

  BUFFALO:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100

  DUCK:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 100
    GRASS: 100

  CATERPILLAR:
    WOLF: 0
    BOA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    GRASS: 100